const defaultProjects=[{name:'VendaCertaAI',type:'Loja virtual',status:'Publicado',updated:'Atualizado hoje',theme:'purple'},{name:'Agenda Bela',type:'Agendamentos',status:'Rascunho',updated:'Atualizado há 2 dias',theme:'blue'},{name:'Finanças Fácil',type:'Controle financeiro',status:'Publicado',updated:'Atualizado há 4 dias',theme:'pink'}];
const templates=[{name:'Loja online',desc:'Catálogo, carrinho e pedidos.',theme:'purple',icon:'🛍️'},{name:'Agendamentos',desc:'Horários, clientes e serviços.',theme:'blue',icon:'📅'},{name:'Portfólio profissional',desc:'Mostre seu trabalho com estilo.',theme:'pink',icon:'✨'},{name:'Controle financeiro',desc:'Organize entradas e despesas.',theme:'green',icon:'📊'},{name:'Comunidade',desc:'Um espaço para seus membros.',theme:'orange',icon:'💬'},{name:'Curso online',desc:'Conteúdo e área do aluno.',theme:'purple',icon:'🎓'}];
let projects=JSON.parse(localStorage.getItem('forge_projects')||'null')||defaultProjects;let currentProject=null;
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function save(){localStorage.setItem('forge_projects',JSON.stringify(projects));}
function projectCard(p){return `<article class="project-card" data-name="${p.name.toLowerCase()}"><div class="project-thumb thumb-${p.theme}"><div class="mini-ui"></div><span class="status-badge ${p.status==='Rascunho'?'draft':''}">${p.status}</span></div><div class="project-info"><strong>${p.name}</strong><small>${p.type}</small><div class="project-footer"><small>${p.updated}</small><button class="open-project" data-project="${p.name}" title="Abrir">→</button></div></div></article>`}
function renderProjects(){let html=projects.map(projectCard).join('');$('#recentProjects').innerHTML=html;$('#allProjects').innerHTML=html;$('#statProjects').textContent=projects.length;$$('.open-project').forEach(b=>b.onclick=()=>openEditor(projects.find(p=>p.name===b.dataset.project)));}
function renderTemplates(){$('#templateGrid').innerHTML=templates.map(t=>`<article class="template-card"><div class="template-cover thumb-${t.theme}"><div class="template-preview ${t.theme==='blue'?'tp-dark':''}"><strong>${t.icon} ${t.name}</strong><div></div><div></div></div></div><div class="template-card-info"><strong>${t.name}</strong><p>${t.desc}</p><button class="use-template" data-template="${t.name}">Usar template →</button></div></article>`).join('');$$('.use-template').forEach(b=>b.onclick=()=>{openNew();$('#appPrompt').value=`um aplicativo de ${b.dataset.template.toLowerCase()}`});}
function navigate(page){$$('.page').forEach(p=>p.classList.remove('active-page'));$(`#page-${page}`).classList.add('active-page');$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===page));$('#breadcrumbs').textContent={dashboard:'Visão geral',projects:'Meus aplicativos',templates:'Templates',settings:'Configurações'}[page];$('.sidebar').classList.remove('open');}
function openNew(){$('#newProjectModal').classList.add('open');setTimeout(()=>$('#appPrompt').focus(),100)}
function closeNew(){$('#newProjectModal').classList.remove('open')}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function openEditor(project){currentProject=project||{name:'Meu aplicativo',type:'Aplicativo personalizado'};$('#editorProjectName').childNodes[0].textContent=currentProject.name+' ';$('#propName').value=currentProject.name;$('#previewBrand').textContent=currentProject.name;$('#previewTitle').innerHTML=(currentProject.name==='VendaCertaAI'?'Sua vendedora<br>profissional com IA.':'Tudo para<br>facilitar seu dia.');$('#editorModal').classList.add('open');}
async function generate(){const prompt=$('#appPrompt').value.trim();if(!prompt){showToast('Descreva sua ideia primeiro.');return}let name=prompt.split(' ').slice(0,3).map(w=>w.charAt(0).toUpperCase()+w.slice(1)).join(' ');if(name.length<4)name='Meu aplicativo';const btn=$('#generateBtn');btn.disabled=true;btn.innerHTML='Gerando projeto...';try{const response=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,prompt})});if(!response.ok)throw new Error('offline');const data=await response.json();currentProject={...data.project,updated:'Criado agora'};projects.unshift(currentProject);save();renderProjects();closeNew();openEditor(currentProject);showToast('Aplicativo criado de verdade: arquivos gerados ✦')}catch(e){currentProject={name,type:'Protótipo local',status:'Rascunho',updated:'Criado agora',theme:['purple','blue','pink'][projects.length%3]};projects.unshift(currentProject);save();renderProjects();closeNew();openEditor(currentProject);showToast('Modo visual ativado. Rode server.py para gerar os arquivos.')}finally{btn.disabled=false;btn.innerHTML='Gerar meu aplicativo <span>→</span>';}}
$$('.nav-item[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page));$$('[data-page]').forEach(b=>{if(!b.classList.contains('nav-item'))b.onclick=()=>navigate(b.dataset.page)});$('#newProjectBtn').onclick=openNew;$('#heroNewBtn').onclick=openNew;$('#projectsNewBtn').onclick=openNew;$$('[data-close]').forEach(b=>b.onclick=closeNew);$('#generateBtn').onclick=generate;$$('[data-suggestion]').forEach(b=>b.onclick=()=>$('#appPrompt').value=b.dataset.suggestion);$('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('open');$('#closeEditor').onclick=()=>$('#editorModal').classList.remove('open');$('#openStudio').onclick=()=>location.href='builder.html';$('#publishBtn').onclick=()=>{if(currentProject){currentProject.status='Publicado';currentProject.updated='Publicado agora';save();renderProjects();$('#editorModal').classList.remove('open');showToast('Aplicativo publicado com sucesso!');}};$('#exportBtn').onclick=()=>{if(currentProject&&currentProject.download){window.location.href=currentProject.download}else showToast('Para exportar arquivos reais, abra o site pelo server.py.');};$('#aiEditBtn').onclick=()=>{const q=prompt('O que você quer alterar no aplicativo?');if(q){showToast('Alteração adicionada ao rascunho: '+q)}};$('#propName').oninput=e=>{$('#previewBrand').textContent=e.target.value;$('#editorProjectName').childNodes[0].textContent=e.target.value+' ';if(currentProject)currentProject.name=e.target.value};$('#projectSearch').oninput=e=>{$$('.project-card').forEach(c=>c.style.display=c.dataset.name.includes(e.target.value.toLowerCase())?'block':'none')};
renderProjects();renderTemplates();
